package com.example.demo.entities;

// default package
// Generated Nov 23, 2017 7:42:03 PM by Hibernate Tools 5.2.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Where;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Category generated by hbm2java
 */
//@Entity
//@Table(name = "category", catalog = "businessin")
//// to dynamic insert and update
//@DynamicInsert
//@DynamicUpdate
//public class Category implements java.io.Serializable {
//
//	private Integer id;
//	private String name;
//	private Integer parentId;
//	private Integer active;
//	private String pic;
//	private Set<Product> products = new HashSet<Product>(0);
//
//	public Category() {
//	}
//
//	public Category(String name, Integer parentId, Integer active, String pic, Set<Product> products) {
//		this.name = name;
//		this.parentId = parentId;
//		this.active = active;
//		this.pic = pic;
//		this.products = products;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "id", unique = true, nullable = false)
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	@Column(name = "name")
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "parentId")
//	public Integer getParentId() {
//		return this.parentId;
//	}
//
//	public void setParentId(Integer parentId) {
//		this.parentId = parentId;
//	}
//
//	@Column(name = "active")
//	public Integer getActive() {
//		return this.active;
//	}
//
//	public void setActive(Integer active) {
//		this.active = active;
//	}
//
//	@Column(name = "pic")
//	public String getPic() {
//		return this.pic;
//	}
//
//	public void setPic(String pic) {
//		this.pic = pic;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category" ,  cascade = CascadeType.ALL)
////	@JsonIgnore
//	public Set<Product> getProducts() {
//		return this.products;
//	}
//
//	public void setProducts(Set<Product> products) {
//		this.products = products;
//	}
//
//}

//
//@Where(clause = "active =1")
//@Entity
//@Table(name = "category", catalog = "businessin")
//// to dynamic insert and update
//@DynamicInsert
//@DynamicUpdate
//public class Category implements java.io.Serializable {
//
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//	@Column(name = "id", unique = true, nullable = false)
//	private Integer id;
//	private String name;
//	private Integer active = 1;
//	private String pic;
//	@JsonIgnore
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category" , cascade = CascadeType.ALL)
//	private List<Product> products = new ArrayList<>();
//	@ManyToOne
//	@JoinColumn(name = "parent_id", columnDefinition = "int default 0" )
//	@ColumnDefault("0")
//	@JsonIgnore
//
//	private Category parentId;
//	@OneToMany(fetch = FetchType.LAZY,  mappedBy = "parentId"  )
//	@JsonIgnore
//	private List<Category> subCategories = new ArrayList<>();
//
//
//	public Integer getId() {
//		return id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public String getName() {
//		return name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	public Integer getActive() {
//		return active;
//	}
//
//	public void setActive(Integer active) {
//		this.active = active;
//	}
//
//	public String getPic() {
//		return pic;
//	}
//
//	public void setPic(String pic) {
//		this.pic = pic;
//	}
//
//	public List<Product> getProducts() {
//		return products;
//	}
//
//	public void setProducts(List<Product> products) {
//		this.products = products;
//	}
//
//	public Category getParentId() {
//		return parentId;
//	}
//
//	public void setParentId(Category parentId) {
//		this.parentId = parentId;
//	}
//
//	public List<Category> getSubCategories() {
//		return subCategories;
//	}
//
//	public void setSubCategories(List<Category> subCategories) {
//		this.subCategories = subCategories;
//	}
//}



import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.springframework.data.jpa.repository.Query;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.Where;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Category generated by hbm2java
 */
@Where(clause = "active =1")
@Entity
@Table(name = "category" )
public class Category implements java.io.Serializable {


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	private String name;
	@Column(nullable=false,columnDefinition="int default 1")
	private Integer active;
	private String pic;
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category" )
	private List<Product> products = new ArrayList<Product>();
	@ManyToOne
	@JoinColumn(name="parent_id" )
	@JsonIgnore
	// @ColumnDefault("0")
	private Category parentId;
	@OneToMany(mappedBy="parentId" )
	@JsonIgnore
	private List<Category> subCategories=new ArrayList<>();



	public Category getParentId() {
		return parentId;
	}

	public List<Category> getSubCategories() {
		return subCategories;
	}

	public void setSubCategories(List<Category> subCategories) {
		this.subCategories = subCategories;
	}

	public void setParentId(Category parentId) {
		this.parentId = parentId;
	}

	public Category() {
	}

	public Category(Category parentId) {
		this.parentId = parentId;
	}

	public Category(String name, Integer parentId, Integer active, String pic, List<Product> products) {
		this.name = name;

		this.active = active;
		this.pic = pic;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	// @Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	// @Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	// @Column(name = "pic")
	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}




